# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1040, 731)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(-190, 310, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.btnRotateLeft = QtWidgets.QPushButton(self.centralwidget)
        self.btnRotateLeft.setGeometry(QtCore.QRect(710, 650, 81, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRotateLeft.sizePolicy().hasHeightForWidth())
        self.btnRotateLeft.setSizePolicy(sizePolicy)
        self.btnRotateLeft.setObjectName("btnRotateLeft")
        self.btnRotateRight = QtWidgets.QPushButton(self.centralwidget)
        self.btnRotateRight.setGeometry(QtCore.QRect(800, 650, 81, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 16, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 16, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 16, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.btnRotateRight.setPalette(palette)
        self.btnRotateRight.setObjectName("btnRotateRight")
        self.btnHistogram = QtWidgets.QPushButton(self.centralwidget)
        self.btnHistogram.setGeometry(QtCore.QRect(610, 650, 91, 31))
        self.btnHistogram.setObjectName("btnHistogram")
        self.btnResize = QtWidgets.QPushButton(self.centralwidget)
        self.btnResize.setGeometry(QtCore.QRect(440, 660, 75, 23))
        self.btnResize.setObjectName("btnResize")
        self.checkBoxAutoRatio = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxAutoRatio.setGeometry(QtCore.QRect(360, 660, 81, 21))
        self.checkBoxAutoRatio.setChecked(True)
        self.checkBoxAutoRatio.setObjectName("checkBoxAutoRatio")
        self.labelPx = QtWidgets.QLabel(self.centralwidget)
        self.labelPx.setGeometry(QtCore.QRect(500, 630, 16, 16))
        self.labelPx.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPx.setObjectName("labelPx")
        self.splitter_3 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_3.setGeometry(QtCore.QRect(440, 610, 51, 41))
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.labelWidth = QtWidgets.QLabel(self.splitter_3)
        self.labelWidth.setObjectName("labelWidth")
        self.lineEditWidth = QtWidgets.QLineEdit(self.splitter_3)
        self.lineEditWidth.setObjectName("lineEditWidth")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(360, 610, 51, 41))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.labelHeight = QtWidgets.QLabel(self.splitter)
        self.labelHeight.setObjectName("labelHeight")
        self.lineEditHeight = QtWidgets.QLineEdit(self.splitter)
        self.lineEditHeight.setObjectName("lineEditHeight")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(100, 0, 851, 601))
        #self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.photo = QtWidgets.QLabel()
        self.photo.setObjectName("photo")
        self.photo.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setWidget(self.photo)
        self.photo.setScaledContents(True)
        self.photo.resize(60 , 40)
        self.photo.setSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored) # for scale in fit_to_window_size mode without scrollbars
        self.checkBoxFitToWindowSize = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxFitToWindowSize.setGeometry(QtCore.QRect(740, 610, 141, 21))
        self.checkBoxFitToWindowSize.setObjectName("checkBoxFitToWindowSize")
        self.splitter_4 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_4.setGeometry(QtCore.QRect(120, 660, 211, 24))
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.percentage = QtWidgets.QLabel(self.splitter_4)
        self.percentage.setObjectName("percentage")
        self.percentage.setGeometry(0,0,33,24)
        self.percentage.setAlignment(QtCore.Qt.AlignCenter)
        self.btnZoomIn = QtWidgets.QPushButton(self.splitter_4)
        self.btnZoomIn.setGeometry(38,0,84,24)
        self.btnZoomIn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/magnifier_plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnZoomIn.setIcon(icon)
        self.btnZoomIn.setObjectName("btnZoomIn")
        self.btnZoomOut = QtWidgets.QPushButton(self.splitter_4)
        self.btnZoomOut.setGeometry(127,0,84,24)
        self.btnZoomOut.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("res/magnifier_minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnZoomOut.setIcon(icon1)
        self.btnZoomOut.setObjectName("btnZoomOut")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1040, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuFilters = QtWidgets.QMenu(self.menuBar)
        self.menuFilters.setObjectName("menuFilters")
        self.menuOther = QtWidgets.QMenu(self.menuBar)
        self.menuOther.setObjectName("menuOther")
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionFilterBlur = QtWidgets.QAction(MainWindow)
        self.actionFilterBlur.setObjectName("actionFilterBlur")
        self.actionFilterGreyscale = QtWidgets.QAction(MainWindow)
        self.actionFilterGreyscale.setObjectName("actionFilterGreyscale")
        self.actionFilterInvert = QtWidgets.QAction(MainWindow)
        self.actionFilterInvert.setObjectName("actionFilterInvert")
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.actionFilterNoise = QtWidgets.QAction(MainWindow)
        self.actionFilterNoise.setObjectName("actionFilterNoise")
        self.actionFilterSmooth = QtWidgets.QAction(MainWindow)
        self.actionFilterSmooth.setObjectName("actionFilterSmooth")
        self.actionFilterSmoothMore = QtWidgets.QAction(MainWindow)
        self.actionFilterSmoothMore.setObjectName("actionFilterSmoothMore")
        self.actionFilterSharpen = QtWidgets.QAction(MainWindow)
        self.actionFilterSharpen.setObjectName("actionFilterSharpen")
        self.actionFilterGaussianBlur = QtWidgets.QAction(MainWindow)
        self.actionFilterGaussianBlur.setObjectName("actionFilterGaussianBlur")
        self.actionFilterEmboss = QtWidgets.QAction(MainWindow)
        self.actionFilterEmboss.setObjectName("actionFilterEmboss")
        self.actionFilterFindEdges = QtWidgets.QAction(MainWindow)
        self.actionFilterFindEdges.setObjectName("actionFilterFindEdges")
        self.actionFilterBoxBlur = QtWidgets.QAction(MainWindow)
        self.actionFilterBoxBlur.setObjectName("actionFilterBoxBlur")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFilters.addAction(self.actionFilterBlur)
        self.menuFilters.addAction(self.actionFilterGreyscale)
        self.menuFilters.addAction(self.actionFilterInvert)
        self.menuFilters.addAction(self.actionFilterNoise)
        self.menuFilters.addAction(self.actionFilterSmooth)
        self.menuFilters.addAction(self.actionFilterSmoothMore)
        self.menuFilters.addAction(self.actionFilterSharpen)
        self.menuFilters.addAction(self.actionFilterGaussianBlur)
        self.menuFilters.addAction(self.actionFilterEmboss)
        self.menuFilters.addAction(self.actionFilterFindEdges)
        self.menuOther.addAction(self.actionReset)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuFilters.menuAction())
        self.menuBar.addAction(self.menuOther.menuAction())

        self.actionSave.setEnabled(False) 
        self.actionFilterBlur.setEnabled(False)
        self.btnRotateLeft.setEnabled(False)
        self.btnRotateRight.setEnabled(False)
        self.btnHistogram.setEnabled(False)
        self.menuFilters.setEnabled(False)
        self.menuOther.setEnabled(False)
        self.actionSave.setEnabled(False)
        self.btnResize.setEnabled(False)
        self.checkBoxAutoRatio.setEnabled(False)
        self.btnZoomIn.setEnabled(False)
        self.btnZoomOut.setEnabled(False)
        self.checkBoxFitToWindowSize.setEnabled(False)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Simple Photo Editor"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.btnRotateLeft.setText(_translate("MainWindow", "↺ 90°"))
        self.btnRotateRight.setText(_translate("MainWindow", "↻ 90°"))
        self.btnHistogram.setText(_translate("MainWindow", "Histogram"))
        self.btnResize.setText(_translate("MainWindow", "Resize"))
        self.checkBoxAutoRatio.setText(_translate("MainWindow", "Auto Ratio"))
        self.labelPx.setText(_translate("MainWindow", "px"))
        self.labelWidth.setText(_translate("MainWindow", "Width:"))
        self.labelHeight.setText(_translate("MainWindow", "Height:"))
        self.photo.setText(_translate("MainWindow", "TextLabel"))
        self.checkBoxFitToWindowSize.setText(_translate("MainWindow", "Fit Image to Window size"))
        self.percentage.setText(_translate("MainWindow" , " "))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuFilters.setTitle(_translate("MainWindow", "Filters"))
        self.menuOther.setTitle(_translate("MainWindow", "Edit"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setStatusTip(_translate("MainWindow", "Choose an image file to open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setStatusTip(_translate("MainWindow", "Save an image file"))
        self.actionFilterBlur.setText(_translate("MainWindow", "Blur"))
        self.actionFilterGreyscale.setText(_translate("MainWindow", "Greyscale"))
        self.actionFilterInvert.setText(_translate("MainWindow", "Invert"))
        self.actionReset.setText(_translate("MainWindow", "Reset"))
        self.actionReset.setStatusTip(_translate("MainWindow", "Reset to original image"))
        self.actionFilterNoise.setText(_translate("MainWindow", "Noise"))
        self.actionFilterSmooth.setText(_translate("MainWindow", "Smooth"))
        self.actionFilterSmoothMore.setText(_translate("MainWindow", "Smooth More"))
        self.actionFilterSharpen.setText(_translate("MainWindow", "Sharpen"))
        self.actionFilterGaussianBlur.setText(_translate("MainWindow", "Gaussian Blur"))
        self.actionFilterEmboss.setText(_translate("MainWindow", "Emboss"))
        self.actionFilterFindEdges.setText(_translate("MainWindow", "Find Edges"))
        self.actionFilterBoxBlur.setText(_translate("MainWindow", "Box Blur"))
